[TOC]

# 异常

异常机制其实是帮助我们找到程序中的问题，异常的根类是 `java.lang.Throwable` 其下有两个子类` java.lang.Error`与`java.lang.Exception `平常所说的异常指`java.lang.Exception`

## 异常分类

java.lang.Throwable:类是java语言中所有错误或异常的超类。

 **Exception**：编译期异常，进行编译（写代码）Java程序出现的问题

**RuntimeException**:运行期异常，Java程序运行过程中出现的问题

​           异常就相当于程序得了一个小毛病（感冒 发烧）把异常处理掉，程序可以继续执行（吃点药继续执行工作）

**Error**:错误

​           错误就相当于程序得了一个无法治愈的毛病（非典 艾滋）<font color=green>必须修改代码</font>，程序才能继续执行。 

```java
 SimpleDateFormat simpleDate=new SimpleDateFormat("yyyy-MM-dd");
        try {
            System.out.println(simpleDate.parse("2003-30"));//格式错误 ParseException
        } catch (ParseException e) {
            e.printStackTrace();
        }
        System.out.println("后续代码");


int[] ary = {1,2,3};
        System.out.println(ary[3]);
//        ArrayIndexOutOfBoundsException  RuntimeException


int[] ary =new int[1024*1024*1024];
//        OutOfMemoryError 只能修改源代码
```

## 异常产生的过程解析

```java
public class viod main(String args[]){
    int[] ary = {1,2,3};
     getElements(ary,3);//产生异常
}
public static int getElement(int[] ary,int index){
    int ele=ary[index];]
        return ele;
}

```

步骤：

1. 访问了数组中的3索引，而数组是没有3索引的，这时候，JVM就检测出程序会出现异常 JVM会做两件事

   1. JVM会根据异常产生的原因创建一个异常对象，这个异常对象包含了异常产生的（<font color=red>内容，原因，位置</font>）

      **<font color=red>new ArrayIndexOutOfBoundsException("3");</font>**

   2. 在getElement方法中，没有异常的处理逻辑（try...catch）,那么就把异常对象抛出给方法的调用者<font color=red>main</font>来处理这个异常

2. main方法接受到了这个异常对象，main方法也没有异常的处理逻辑继续把对象抛出给main方法的调用者JVM处理

3. JVM接受到了这个异常对象，做了两件事

   1. 把异常对象（内容，原因，位置）以红色的字体打印在控制台
   2. JVM会终止当前正在执行的java程序--><font color=red>中断处理</font>

## throw关键字

作用： 可以使用throw关键字在指定的方法中抛出异常

使用格式：  `throw new xxxException`("异常产生的原因");

注意:

1. throw关键字必须写在方法的内部
2. throw关键字后边new的对象必须是Exception或者是Exception的子类
3. throw关键字抛出指定的异常对象，就必须处理这个异常对象
   1. throw关键字后边创建的是RuntimeException或者是RuntimeException的子类对象，我们可以不处理，默认交给JVM处理（打印异常对象，中断程序）
   2. throw关键字后边创建的是编译异常，我们就必须处理这个异常，要么throws 要么try...catch

## Objects类中的静态方法 requireNonNull( )非空判断

```java
public static <T> T requireNonNull(T obj)：查看指定引用对象不是null.
 //   源码：
    public static <T> T requireNonNull(T obj){
    if(obj==null)
        throw new NullPointerException();
    return obj;
}
    Objects.requireNonNull(Object obj,String message)
```

## throws关键字 异常处理

异常处理的第一种方式，交给别人处理

**作用**：当方法内部抛出异常对象的时候那么我们就必须处理这个异常对象

​             可以使用throws关键字处理异常对象，会把异常对象声明抛出给方法的调用者处理（自己不处理，给别人处理），最终交给JVM处理-->中断处理

<!--会有一个弊端：交给JVM处理后会中断处理 不会执行后续代码-->

**使用格式**：在方法声明时使用

`修饰符 返回值类型 方法名（参数列表） throws AAAException，BBBException...`{

​                  ` throw new AAAException("产生原因");`

​                   `throw new BBBException("产生原因");`

}

注意：

1. throws关键字必须写在方法声明处

2. throws关键字后边声明必须是Exception或者是Exception的子类

3. 方法内部如果抛出了多个异常对象，那么throws后边必须也声明多个异常

   如果抛出的多个异常对象有子父类关系，那么直接声明父类异常即可

4. 调用了一个声明抛出异常的方法，我们就必须处理声明的异常

     要么继续使用throws声明抛出，给方法的调用者处理

     要么try...catch 自己处理

   ```java
   public static void main(String[] args) throws IOException {
           ReadFile("c:\\\\a.xt");
       }
       /*
           定义一个方法，对传递的文件路径进行合法性判断
           如果路径不是"c:\\a.txt",那么我们就抛出 文件找不到异常对象，告知方法的调用者
           注意：
           FileNotFoundException是编译异常，抛出了编译异常，就必须处理这个异常
           可以使用throws继续声明抛出FileNotFoundException这个异常对象，
           让方法的调用者处理
            */
       private static void ReadFile(String filename) throws /*FileNotFoundException*/IOException {
           /*
           FileNotFoundException extends IOException
           如果抛出的多个异常对象有子父类关系，那么直接声明父类异常即可      */
           if (!filename.equals("c:\\\\a.")){
               throw new FileNotFoundException("传递的文件路径不是 c:\\\\a.txt");
           }
           System.out.println("传递的路径没有问题");
           /*
           如果传递到，不是.txt结尾
           那么我们就抛出IO异常对象告知方法的调用者，文件的后缀名不对*/
           if (!filename.endsWith(".txt"))
               throw new IOException("文件的后缀名不对");
       }
   ```

   ## try...catch异常处理

   异常处理的第二种方法，自己处理异常

   **格式**：

   ```java
   try{
       可能产生的异常的代码
   }catch(定义一个异常的变量，来接受try中抛出的异常对象){
       异常的处理逻辑，产生异常对象之后，怎么处理异常对象
        一般在工作中，会把异常的信息记录到一个日志中
   }
   ...
       catch(异常类名 异常名){
           
       }
   ```

   `注意`；

1. try中可能会抛出多个异常对象，那么就可以使用多个catch来处理这些异常对象

2. 如果try中产生了异常，那么就会执行catch中的异常处理逻辑，执行完毕catch中的处理逻辑，**继续执行try...catch之后的代码**

   如果try中没有产生异常，那么就不会执行catch中异常处理逻辑，执行完try中的代码，**继续执行try...catch之后的代码**

Throwable类中定义了3个处理异常的方法

```java
String getMessage() 返回此throwable 的简短描述
String toString()   返回此 throwable 的详细消息字符串
void printStackTrace() JVM打印异常对象，默认此方法 得到的信息是最全面的
```

## 多个异常处理

1. 多个异常分别处理

   ```java
   try{
               int[] arr={1,2,3};
      System.out.println(arr[3]);//ArrayIndexOutOfBoundsException
           }catch(ArrayIndexOutOfBoundsException e){
               e.printStackTrace();
           }
           try{
               List<Object> of = List.of(1,2,3);
               System.out.println(of.get(3));//IndexOutOfBoundsException
           }catch(IndexOutOfBoundsException e){
               e.printStackTrace();
           }
   ```

   

2. 多个异常一次捕获，多次处理

   ```java
    try{
               int[] arr={1,2,3};
               System.out.println(arr[3]);//ArrayIndexOutOfBoundsException
               
               List<Object> of = List.of(1,2,3);
               System.out.println(of.get(3));//IndexOutOfBoundsException
           }catch(ArrayIndexOutOfBoundsException e){
               e.printStackTrace();
           } catch(IndexOutOfBoundsException e){
               e.printStackTrace();
           }
   反过来会报错
   ```

   > 一个try多个catch注意事项：
   >
   > catch里边定义的异常变量，如果有父子类关系，那么子类的异常变量必须写在边上，否则就会报错

   原因；	

   ![](https://i.bmp.ovh/imgs/2022/01/9a8fc15ff9cea4fa.png)

3. 多个异常一次捕获一次处理

```java
try {
            int[] arr = {1, 2, 3};
            System.out.println(arr[3]);//ArrayIndexOutOfBoundsException

            List<Object> of = List.of(1, 2, 3);
            System.out.println(of.get(3));//IndexOutOfBoundsException
        } catch (Exception e) {
            e.printStackTrace();
```

运行期异常抛出可以不处理，交给JVM处理

### 异常注意事项 

#### finally

如果finally有return语句，永远返回finally中的结果，避免该情况应该 少在finally中加return语句

#### 子父类异常

1. 如果父类抛出了多个异常，子类重写父类方法时，抛出和父类相同的异常或者是父类异常的子类或者不抛出异常
2. 父类方法没有抛出异常，子类重写父类方法时也不可抛出异常。此时子类产生该异常，只能捕获处理，不能声明抛出

注意：父类异常时什么样，子类异常就什么样

### 自定义异常类（RegisterException）

java提供的异常类，不够我们使用，需要自己定义一些异常类

`格式`:

```java
public class XXXException extends Exception|RuntimeException{
    //添加一个空参数的构造方法
    //添加一个带异常信息的构造方法
}
```

注意：

1. 自定义异常类一般都是以Exception结尾，说明该类是一个异常类

2. 自定义异常类，必须继承Exception或者RuntimeException

   继承Exception：那么自定义的异常类就是一个编译期异常，如果方法内部抛出了编译期异常，就必须处理它 要么throws 要么try...catch

   继承RuntimeException：那么自定义的异常就是一个运行期异常，无序处理，交给虚拟机处理（中断处理）

#### 练习

要求：我们模拟注册操作，如果用户名已存在，则抛出异常并提示：亲，该用户名已被注册

![](https://i.bmp.ovh/imgs/2022/01/76523c8cb26d0aa4.png)
